export default [
  {
    command: "extension.openIndexOf",
    type: "href",
    url: "https://pd.dev.wyyt.cc/",
    title: "产品原型",
  },
  {
    command: "extension.openServe",
    type: "href",
    url: "http://192.168.6.14:8080/",
    title: "内网服务汇总",
  },
  {
    command: "extension.openKdocs",
    type: "href",
    url: "https://www.kdocs.cn/team/1787108889?fileId=172379663454",
    title: "金山文档团队空间",
  },
  {
    command: "extension.openYuque",
    type: "href",
    url: "https://appfe.yuque.com/tyl8d3",
    title: "语雀",
  },
  {
    command: "extension.openOA",
    type: "href",
    url: "http://oa.wyyt.com/eoffice10/client/web/portal/1",
    title: "公司OA",
  },
  {
    command: "extension.openWyyt",
    type: "href",
    url: "https://g.wyyt.cc/",
    title: "公司导航系统",
  },
  {
    command: "extension.openJenkins",
    type: "href",
    url: "http://192.168.6.13:8018/jenkins/login?from=%2Fjenkins%2F",
    title: "内网jenkins",
  },
  {
    command: "extension.openGitlab",
    type: "href",
    url: "https://git.wyyt.cc/",
    title: "gitLab",
  },
  {
    command: "extension.openIconfont",
    type: "href",
    url: "https://www.iconfont.cn/home/index",
    title: "阿里巴巴iconfont",
  },
  {
    command: "extension.openPlus",
    type: "href",
    url: "https://element-plus.gitee.io/zh-CN/component/button.html",
    title: "element-plus",
  },
  {
    command: "extension.openElement",
    type: "href",
    url: "https://element.eleme.cn/#/zh-CN/component/installation",
    title: "element-ui",
  },
  {
    command: "extension.openVant",
    type: "href",
    url: "https://vant-contrib.gitee.io/vant/#/zh-CN/home",
    title: "vant-ui",
  },
  {
    command: "extension.openVue3js",
    type: "href",
    url: "https://vue3js.cn/",
    title: "vue3网站汇总",
  },
  {
    command: "extension.openVue3",
    type: "href",
    url: "https://v3.cn.vuejs.org/",
    title: "vue3官网",
  },
  {
    command: "extension.openVue2",
    type: "href",
    url: "https://cn.vuejs.org/v2/guide/",
    title: "vue2官网",
  },
  {
    command: "extension.openDaid",
    type: "href",
    url: "http://id.daidada.cn/",
    title: "身份证号码生成器",
  },
  {
    command: "extension.openJson",
    type: "href",
    url: "https://www.indev.cn/",
    title: "JSON格式化",
  },
  {
    command: "extension.openLibrary",
    type: "img",
    url: "componnetLibrary",
    title: "组件库",
  },
];
